### ISSUE TITLE
[FEAT] - Abstracting sensors 

### ISSUE THREAD

**Issue by stoh1729** [ahmed-nazir/Capstone#41]
It would be nice if users did not have to think about how to connect a sensor from the market to our embedded device.

To do this, the sensor connections need to be abstracted by creating classes of sensors (such as 3 wire, 4 wire, etc.), and then design + CAD + 3D print hardware that supports this abstraction. 

It could look similar to a something used in industrial hardware, where the connection is guided and the user does not necessarily need to know what each of the pins do in order to successfully connect the cable.

![ConnectionExample](https://user-images.githubusercontent.com/90631656/202862532-0fa7bcee-5cfe-4a7c-90c7-3eff96370cca.png)

**Comment by ahmed-nazir** [comment]
We used JST connectors
