### ISSUE TITLE
[ENHANCEMENT] - Allow access to multiple ip addresses to DB

### ISSUE THREAD

**Issue by muhanadsada** [ahmed-nazir/Capstone#52]
**What is the enhancement?**
Allow access to multiple ip addresses such as McMaster's subnet so you don't always have to add individual ip addresses 

**Purpose of the Enhancement?**
It's not feasible to keep adding/updating individual access for each ip address

**Comment by ahmed-nazir** [comment]
Allowed all of mcmaster subnet
