### ISSUE TITLE
Team25 Review - Changes to template not identified

### ISSUE THREAD

**Issue by fahmed8383** [ahmed-nazir/Capstone#6]
For the SRS Document, certain changes that were made to the template such as adding in the phase in plan and the traceability table should be identified at the top. 

It would also be nice to have some information about what the original template was so it is possible to distinguish these changes (however this specifically is not part of the rubric)

**Comment by fahmed8383** [comment]
@samm82

**Comment by ahmed-nazir** [comment]
For Mechatronics students we did not have to follow a specific template, so we created our own based on the rubric and from looking at previous examples
